### ISSUE TITLE
Integrating CastXMR support?

### ISSUE THREAD

**Issue by setsimmo** [randygrolemund/shitcoin-profitmanager#1]
Any chance/roadmap for adding CastXMR support to this program? Would love to use it, but I get much better hashrates on my Vegas via CastXMR vs xmr-stak. Here's a link in case you aren't familiar with the software:

http://www.gandalph3000.com/

**Comment by randygrolemund** [comment]
I'll look in to it, should be easy

**Comment by randygrolemund** [comment]
Hey guys..... I'm working on a completely redesigned version that will be web based, with an agent on each worker. You'll have centralized statistics, control over all your workers from the web, and way more features. I'm not doing any additional major work in v3.x.x -- other than bug fixes, adding new algo's, updating XMR when they release a new version, and some minor tweaks. I do not just write the code, I actually use it too. :)
