### ISSUE TITLE
 Integrating SRB Miner support? 

### ISSUE THREAD

**Issue by alex0987alex** [randygrolemund/shitcoin-profitmanager#4]
https://bitcointalk.org/index.php?topic=3167363.0

**Comment by lamgztey** [comment]
Please build SCPM work with xmr-stak linux ! thanks !

2018-07-07 14:50 GMT+07:00 alex0987alex <notifications@github.com>:

**Comment by randygrolemund** [comment]
Hey guys..... I'm working on a completely redesigned version that will be web based, with an agent on each worker. You'll have centralized statistics, control over all your workers from the web, and way more features. I'm not doing any additional major work in v3.x.x -- other than bug fixes, adding new algo's, updating XMR when they release a new version, and some minor tweaks. I do not just write the code, I actually use it too. :)
