### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by KaiGee1** [randygrolemund/shitcoin-profitmanager#5]
If you enter a path with a directory structure (C:\temp\shitcoin-pm) you get JSON parsing errors.  You need to escape all of the '\' with another '\' so the final path ends up looking like C:\\temp\\shitcoin-pm

**Comment by randygrolemund** [comment]
try double \\ instead. works for all 10 of my rigs.

**Comment by KaiGee1** [comment]
Yep, good to go.  But, I find that the site you use to find best coin isn't configurable enough to match my rigs actually hashrates. So, it isn't worth using your code.

**Comment by randygrolemund** [comment]
Thanks for getting back to me. I think you perhaps misunderstand how the software works, it's not based on hash rate at all. It's based on a number of other factors instead. 

https://minecryptonight.net/api/best

**Comment by randygrolemund** [comment]
This one is used w/ hashrate. I could make something like this an option.

https://minecryptonight.net/api/rewards?hr=32000

**Comment by randygrolemund** [comment]
If you copy and paste this to a new powershell file on your pc.... would this work better?

$get_coin = Invoke-RestMethod -Uri "https://minecryptonight.net/api/rewards?hr=16000" -Method Get
$Array = $get_coin.rewards

$Array[1]
$symbol = $array.ticker_symbol[0]
$coins = $Array.reward_24h.coins[0]
$usd = $Array.reward_24h.usd[0]

Write-host "Symbol: $symbol, Coins: $coins, USD: $usd"

**Comment by randygrolemund** [comment]
Of course.... you would put in your total CN7 hashrate.... from there they determine fast and heavy speeds

**Comment by randygrolemund** [comment]
![image](https://user-images.githubusercontent.com/8581255/43715097-ebea53e0-9944-11e8-81eb-df18875c87f7.png)

**Comment by KaiGee1** [comment]
I investigated doing something like this myself already.  The issue that still remains is that the minecryptonight website api has no way (that I could find) to set different factors (speeds) for the different cn algos.  My rig mines regular cn-v7 at 5.15 kH/s and cn-heavy at 4.2 kH/s.  That ratio is 4.2/5.15 = 0.82 and the website api uses 0.6.  I mine cn-fast at 10.05 kH/s for a ratio of 1.95 compared to the api factor of 1.8.  The differences in the api factors and my factors make it impossible to pick the correct coin for me.  I would expect for you as well.

**Comment by randygrolemund** [comment]
You don't have to be EXACTLY accurate down to the single digit hashrate.
None of them are... even the paid ones.

I actually get better performance using my software, than the $175 version
of Awesome Miner, that I bought in January.

It sounds to me like you want high accuracy, which you likely won't find.
The pool sites give diff calculations than the profitability sites
(cryotunit, minecryptonight, etc) , which give different results than the
purchased mining software.

If you have better ideas... I'm all ears for making improvements. I
initially wrote this to be simple, and for myself. I use to spend too much
time trying to figure out the best coin to mine.... only to find it changed
a few minutes later. I wanted something that was more automated, and closer
to real time.

All the site claim that you should query them every 10+ mins.... you cannot
be highly accurate with that kind of window.

I used to query every minute but they eventually banned my IP.

**Comment by randygrolemund** [comment]
I suppose you already know about advanced settings on the site?

![image](https://user-images.githubusercontent.com/8581255/43732623-cd1bb67e-9977-11e8-868f-e0b3c10cd2cf.png)

**Comment by randygrolemund** [comment]
I recently found this site..... looking in to ways to connect to their API.... maybe you will like this better?
https://triforcecoin.com/

**Comment by randygrolemund** [comment]
Hey... I wanted to update you... I'm almost done designing a new profit calculator. You'll be able to tweak it as much as you want. It'll run on each worker, and figure out based on the workers performance, which coin is the most profitable.

Here's an example

![image](https://user-images.githubusercontent.com/8581255/43996857-c809d846-9d91-11e8-9d96-cadac917fa82.png)
